# .github/workflows/python-ci.yml

name: Python CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # Install the SDK from the robocore-api-python folder in editable mode
          python -m pip install -e "./robocore-api-python[dev]"

      - name: Run tests
        working-directory: robocore-api-python
        run: pytest --maxfail=1 --disable-warnings -q

      - name: Lint
        working-directory: robocore-api-python
        run: flake8 robocore_api
