name: Python CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # Install your SDK (from the subfolder) with dev extras
          pip install -e "./robocore-api[dev]"

      - name: Run tests
        run: pytest --maxfail=1 --disable-warnings -q

      - name: Lint
        run: flake8 robocore-api/robocore_api
